Pages/profile
teletubby-v-2/front pull request #18
Opened 2021-08-05 15:56 UTC by numkhang

###  UI

- สิ่งที่ทำ...
- MyProfile ( Profile และ Edit )
- **ยังไม่มี function ของ form / upload profile pic

### FUNCTION

- สิ่งที่ทำ...
- เปลี่ยน displayName เป็น userName

2021-08-05 16:53 UTC, JAmoMES requested changes

2021-08-05 16:53 UTC, JAmoMES commented on src/App.tsx
> +            <Redirect to="/success" />
go to login

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/EditComponent.tsx
> +            <Upload>
upload ยังใช้ไม่ได้เขียน todo ไว้หน่อย

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/EditComponent.tsx
> +            <Upload>
// TODO: ..........

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/EditComponent.tsx
> +export function EditComponent({ onfin }: any) {
สร้างinterfaceของ propsหน่อย สร้าง type ของ. onfin

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/EditComponent.tsx
> +export function EditComponent({ onfin }: any) {
onFinish

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/EditComponent.tsx
> +export function EditComponent({ onfin }: any) {
อ่าพยายามตั้งให้มีความหมายนิดนึง

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/ProfileComponent.tsx
> +export const ProfileComponent: React.FC<ProfileComponentProps> = props => {
สร้างแบบนี้

2021-08-05 16:53 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/index.tsx
> +export function MyProfile() {
สร้าง type React.FC

2021-08-05 16:54 UTC, JAmoMES commented
อันไหนยังเหลือที่ต้องทอยู่เขียนTODO ให้หน่อย

2021-08-05 16:54 UTC, JAmoMES commented
พยายามใช้ anyให้น้อยที่สุด

2021-08-05 17:41 UTC, numkhang commented on src/pages/Profile/components/MyProfile/ProfileComponent.tsx
> +export const ProfileComponent: React.FC<ProfileComponentProps> = props => {
ทำแบบนี้แล้วมัน callback จาก function ไม่ได่  แก้ยังไงอะ

2021-08-05 17:42 UTC, numkhang commented on src/pages/Profile/components/MyProfile/ProfileComponent.tsx
> +export const ProfileComponent: React.FC<ProfileComponentProps> = props => {
const onFinish = (value: UpdateValue) => {
    props.onClose
    console.log(value)
    /* TODO: update profile */
  }
เรียก  props.onClose แล้วแต่ไม่ไป

2021-08-06 04:56 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/ProfileComponent.tsx
> +export const ProfileComponent: React.FC<ProfileComponentProps> = props => {
อันนี้หมายถึงตรงไหน
หลักๆ คือพยายามใช้ callbackให้น้อยที่สุด เพราะแก้บัคยาก

2021-08-06 04:57 UTC, JAmoMES commented on src/pages/Profile/components/MyProfile/ProfileComponent.tsx
> +export const ProfileComponent: React.FC<ProfileComponentProps> = props => {
onClose เป็น ฟังก์ชั่น typeจะเป็น ( param: typeof param )=> typeof return

2021-08-22 11:22 UTC, JAmoMES commented
ลองเชคแล้วมันเพิ่มค่าแล้วไม่ขึ้นปะ

2021-08-22 11:36 UTC, JAmoMES commented
ลองเพิ่ม about meแล้วมันไม่มาอะ

2021-08-22 11:38 UTC, numkhang commented
ยังไม่ได้ใส่ function update

2021-08-23 09:41 UTC, merged